"""add authentication and student profile

Revision ID: 17c7cad1b896
Revises: dfd51c9cc781
Create Date: 2026-07-27 14:27:30.496964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17c7cad1b896'
down_revision: Union[str, Sequence[str], None] = 'dfd51c9cc781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index(op.f('ix_refresh_tokens_token_id'), 'refresh_tokens', ['token_id'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index('ix_refresh_tokens_user_id_is_revoked', 'refresh_tokens', ['user_id', 'is_revoked'], unique=False)
    op.create_table('student_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('grade_level', sa.Integer(), nullable=False),
    sa.Column('school_name', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('preferred_learning_mode', sa.Enum('theory_first', 'practice_first', 'step_by_step', 'balanced', name='learning_mode'), nullable=False),
    sa.Column('explanation_depth', sa.Enum('short', 'medium', 'detailed', name='explanation_depth'), nullable=False),
    sa.Column('preferred_session_minutes', sa.Integer(), nullable=False),
    sa.Column('study_days_per_week', sa.Integer(), nullable=False),
    sa.Column('study_minutes_per_day', sa.Integer(), nullable=False),
    sa.Column('favourite_subjects', sa.Text(), nullable=True),
    sa.Column('difficult_subjects', sa.Text(), nullable=True),
    sa.Column('learning_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('grade_level >= 1 AND grade_level <= 12', name=op.f('ck_student_profiles_grade_level_range')),
    sa.CheckConstraint('preferred_session_minutes >= 10 AND preferred_session_minutes <= 180', name=op.f('ck_student_profiles_session_minutes_range')),
    sa.CheckConstraint('study_days_per_week >= 1 AND study_days_per_week <= 7', name=op.f('ck_student_profiles_study_days_range')),
    sa.CheckConstraint('study_minutes_per_day >= 10 AND study_minutes_per_day <= 600', name=op.f('ck_student_profiles_study_minutes_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_student_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_profiles'))
    )
    op.create_index(op.f('ix_student_profiles_user_id'), 'student_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_profiles_user_id'), table_name='student_profiles')
    op.drop_table('student_profiles')
    op.drop_index('ix_refresh_tokens_user_id_is_revoked', table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
