"""add_course_id_to_exam_analyses

Revision ID: 4105cce10197
Revises: e781f61d9bd7
Create Date: 2026-08-19 04:15:19.882015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4105cce10197'
down_revision: Union[str, Sequence[str], None] = 'e781f61d9bd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_analyses', sa.Column('course_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_exam_analyses_course_id'), 'exam_analyses', ['course_id'], unique=False)
    op.create_foreign_key(op.f('fk_exam_analyses_course_id_courses'), 'exam_analyses', 'courses', ['course_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_exam_analyses_course_id_courses'), 'exam_analyses', type_='foreignkey')
    op.drop_index(op.f('ix_exam_analyses_course_id'), table_name='exam_analyses')
    op.drop_column('exam_analyses', 'course_id')
    # ### end Alembic commands ###
