"""remove_unused_student_profile_learning_mode_fields

Revision ID: 5467b113ab1a
Revises: 4105cce10197
Create Date: 2026-08-19 19:57:19.160300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5467b113ab1a'
down_revision: Union[str, Sequence[str], None] = '4105cce10197'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profiles', 'explanation_depth')
    op.drop_column('student_profiles', 'preferred_learning_mode')
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS explanation_depth")
    op.execute("DROP TYPE IF EXISTS learning_mode")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("CREATE TYPE learning_mode AS ENUM ('theory_first', 'practice_first', 'step_by_step', 'balanced')")
    op.execute("CREATE TYPE explanation_depth AS ENUM ('short', 'medium', 'detailed')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('preferred_learning_mode', postgresql.ENUM('theory_first', 'practice_first', 'step_by_step', 'balanced', name='learning_mode', create_type=False), autoincrement=False, nullable=False, server_default='balanced'))
    op.add_column('student_profiles', sa.Column('explanation_depth', postgresql.ENUM('short', 'medium', 'detailed', name='explanation_depth', create_type=False), autoincrement=False, nullable=False, server_default='medium'))
    # ### end Alembic commands ###
