"""Add personalized_roadmap table

Revision ID: 5b133fef9d1b
Revises: f029c894a90b
Create Date: 2026-08-06 18:25:46.108793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b133fef9d1b'
down_revision: Union[str, Sequence[str], None] = 'f029c894a90b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personalized_roadmaps',
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('exam_analysis_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('overview', sa.Text(), nullable=False),
    sa.Column('total_weeks', sa.Integer(), nullable=False),
    sa.Column('roadmap_data', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['exam_analysis_id'], ['exam_analyses.id'], name=op.f('fk_personalized_roadmaps_exam_analysis_id_exam_analyses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['learner_id'], ['learner_profiles.id'], name=op.f('fk_personalized_roadmaps_learner_id_learner_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_personalized_roadmaps'))
    )
    op.create_index(op.f('ix_personalized_roadmaps_learner_id'), 'personalized_roadmaps', ['learner_id'], unique=False)
    op.drop_constraint(op.f('ck_learner_course_profiles_learner_course_profile_versi_1e67'), 'learner_course_profiles', type_='check')
    op.create_check_constraint(op.f('ck_learner_course_profiles_learner_course_profile_version_positive'), 'learner_course_profiles', 'profile_version >= 1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_learner_course_profiles_learner_course_profile_version_positive'), 'learner_course_profiles', type_='check')
    op.create_check_constraint(op.f('ck_learner_course_profiles_learner_course_profile_versi_1e67'), 'learner_course_profiles', 'profile_version >= 1')
    op.drop_index(op.f('ix_personalized_roadmaps_learner_id'), table_name='personalized_roadmaps')
    op.drop_table('personalized_roadmaps')
    # ### end Alembic commands ###
