"""add_exam_score_and_mastery_history

Revision ID: 8bb7ba46ccfd
Revises: ebf151330860
Create Date: 2026-08-19 04:03:53.927752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bb7ba46ccfd'
down_revision: Union[str, Sequence[str], None] = 'ebf151330860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mastery_history',
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.String(length=255), nullable=False),
    sa.Column('old_score', sa.Float(), nullable=False),
    sa.Column('new_score', sa.Float(), nullable=False),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learner_profiles.id'], name=op.f('fk_mastery_history_learner_id_learner_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mastery_history'))
    )
    op.create_index(op.f('ix_mastery_history_learner_id'), 'mastery_history', ['learner_id'], unique=False)
    op.create_index(op.f('ix_mastery_history_topic_id'), 'mastery_history', ['topic_id'], unique=False)
    op.add_column('exam_analyses', sa.Column('exam_score', sa.Float(), nullable=True))
    op.add_column('exam_analyses', sa.Column('exam_max_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_analyses', 'exam_max_score')
    op.drop_column('exam_analyses', 'exam_score')
    op.drop_index(op.f('ix_mastery_history_topic_id'), table_name='mastery_history')
    op.drop_index(op.f('ix_mastery_history_learner_id'), table_name='mastery_history')
    op.drop_table('mastery_history')
    # ### end Alembic commands ###
