"""remove_unused_student_profile_fields

Revision ID: 964725387c86
Revises: 5b133fef9d1b
Create Date: 2026-08-06 22:00:35.701898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '964725387c86'
down_revision: Union[str, Sequence[str], None] = '5b133fef9d1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_learner_course_profiles_learner_course_profile_versi_1e67'), 'learner_course_profiles', type_='check')
    op.create_check_constraint(op.f('ck_learner_course_profiles_learner_course_profile_version_positive'), 'learner_course_profiles', 'profile_version >= 1')
    op.drop_column('student_profiles', 'city')
    op.drop_column('student_profiles', 'difficult_subjects')
    op.drop_column('student_profiles', 'favourite_subjects')
    op.drop_column('student_profiles', 'learning_notes')
    op.drop_column('student_profiles', 'school_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('school_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('student_profiles', sa.Column('learning_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('student_profiles', sa.Column('favourite_subjects', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('student_profiles', sa.Column('difficult_subjects', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('student_profiles', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('ck_learner_course_profiles_learner_course_profile_version_positive'), 'learner_course_profiles', type_='check')
    op.create_check_constraint(op.f('ck_learner_course_profiles_learner_course_profile_versi_1e67'), 'learner_course_profiles', 'profile_version >= 1')
    # ### end Alembic commands ###
