"""add_education_level_with_university_year

Revision ID: 9b35b227a0b5
Revises: a1560179fa47
Create Date: 2026-08-06 22:18:51.738099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b35b227a0b5'
down_revision: Union[str, Sequence[str], None] = 'a1560179fa47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_learner_course_profiles_learner_course_profile_versi_1e67'), 'learner_course_profiles', type_='check')
    op.create_check_constraint(op.f('ck_learner_course_profiles_learner_course_profile_version_positive'), 'learner_course_profiles', 'profile_version >= 1')
    education_enum = sa.Enum('under_university', 'university', name='education_level')
    # This enum may remain after the previous migration removes its column.
    # checkfirst keeps upgrades idempotent on existing local databases.
    education_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('student_profiles', sa.Column('education_level', education_enum, server_default='under_university', nullable=False))
    op.drop_constraint(op.f('ck_student_profiles_grade_level_range'), 'student_profiles', type_='check')
    op.create_check_constraint(op.f('ck_student_profiles_grade_level_education_check'), 'student_profiles', "(education_level = 'under_university' AND grade_level >= 1 AND grade_level <= 12) OR (education_level = 'university' AND grade_level >= 1 AND grade_level <= 7)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_student_profiles_grade_level_education_check'), 'student_profiles', type_='check')
    op.create_check_constraint(op.f('ck_student_profiles_grade_level_range'), 'student_profiles', 'grade_level >= 1 AND grade_level <= 12')
    op.drop_column('student_profiles', 'education_level')
    op.execute("DROP TYPE education_level")
    op.drop_constraint(op.f('ck_learner_course_profiles_learner_course_profile_version_positive'), 'learner_course_profiles', type_='check')
    op.create_check_constraint(op.f('ck_learner_course_profiles_learner_course_profile_versi_1e67'), 'learner_course_profiles', 'profile_version >= 1')
    # ### end Alembic commands ###
