"""remove_education_level

Revision ID: a1560179fa47
Revises: d3929cfb2383
Create Date: 2026-08-06 22:15:39.728971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1560179fa47'
down_revision: Union[str, Sequence[str], None] = 'd3929cfb2383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_learner_course_profiles_learner_course_profile_versi_1e67'), 'learner_course_profiles', type_='check')
    op.create_check_constraint(op.f('ck_learner_course_profiles_learner_course_profile_version_positive'), 'learner_course_profiles', 'profile_version >= 1')
    op.alter_column('student_profiles', 'grade_level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('ck_student_profiles_grade_level_education_check'), 'student_profiles', type_='check')
    op.create_check_constraint(op.f('ck_student_profiles_grade_level_range'), 'student_profiles', 'grade_level >= 1 AND grade_level <= 12')
    op.drop_column('student_profiles', 'education_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('education_level', postgresql.ENUM('under_university', 'university', name='education_level'), server_default=sa.text("'under_university'::education_level"), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('ck_student_profiles_grade_level_range'), 'student_profiles', type_='check')
    op.create_check_constraint(op.f('ck_student_profiles_grade_level_education_check'), 'student_profiles', "education_level = 'under_university'::education_level AND grade_level >= 1 AND grade_level <= 12 OR education_level = 'university'::education_level AND grade_level IS NULL")
    op.alter_column('student_profiles', 'grade_level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('ck_learner_course_profiles_learner_course_profile_version_positive'), 'learner_course_profiles', type_='check')
    op.create_check_constraint(op.f('ck_learner_course_profiles_learner_course_profile_versi_1e67'), 'learner_course_profiles', 'profile_version >= 1')
    # ### end Alembic commands ###
