"""update_student_profile_grade_level

Revision ID: d3929cfb2383
Revises: 964725387c86
Create Date: 2026-08-06 22:10:16.694912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3929cfb2383'
down_revision: Union[str, Sequence[str], None] = '964725387c86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_learner_course_profiles_learner_course_profile_versi_1e67'), 'learner_course_profiles', type_='check')
    op.create_check_constraint(op.f('ck_learner_course_profiles_learner_course_profile_version_positive'), 'learner_course_profiles', 'profile_version >= 1')
    education_enum = sa.Enum('under_university', 'university', name='education_level')
    education_enum.create(op.get_bind())
    op.add_column('student_profiles', sa.Column('education_level', education_enum, server_default='under_university', nullable=False))
    op.alter_column('student_profiles', 'grade_level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('ck_student_profiles_grade_level_range'), 'student_profiles', type_='check')
    op.create_check_constraint(op.f('ck_student_profiles_grade_level_education_check'), 'student_profiles', "(education_level = 'under_university' AND grade_level >= 1 AND grade_level <= 12) OR (education_level = 'university' AND grade_level IS NULL)")
    op.drop_column('student_profiles', 'date_of_birth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('ck_student_profiles_grade_level_education_check'), 'student_profiles', type_='check')
    op.create_check_constraint(op.f('ck_student_profiles_grade_level_range'), 'student_profiles', 'grade_level >= 1 AND grade_level <= 12')
    op.alter_column('student_profiles', 'grade_level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('student_profiles', 'education_level')
    education_enum = sa.Enum('under_university', 'university', name='education_level')
    education_enum.drop(op.get_bind())
    op.drop_constraint(op.f('ck_learner_course_profiles_learner_course_profile_version_positive'), 'learner_course_profiles', type_='check')
    op.create_check_constraint(op.f('ck_learner_course_profiles_learner_course_profile_versi_1e67'), 'learner_course_profiles', 'profile_version >= 1')
    # ### end Alembic commands ###
