"""upgrade_content_chunk_embedding_to_768d

Revision ID: e781f61d9bd7
Revises: 8bb7ba46ccfd
Create Date: 2026-08-19 04:11:22.828246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'e781f61d9bd7'
down_revision: Union[str, Sequence[str], None] = '8bb7ba46ccfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Đổi embedding từ feature-hash 384-chiều (giả) sang Gemini embedding thật 768-chiều.
    Dữ liệu embedding cũ không tương thích chiều mới nên được xóa (set NULL) — chunk hiện
    có cần rebuild-index lại qua endpoint `POST /courses/versions/{id}/rag/index`.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content_chunks', 'embedding', nullable=True)
    op.execute("UPDATE content_chunks SET embedding = NULL")
    op.alter_column(
        'content_chunks', 'embedding',
        existing_type=Vector(384),
        type_=Vector(768),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE content_chunks SET embedding = NULL")
    op.alter_column(
        'content_chunks', 'embedding',
        existing_type=Vector(768),
        type_=Vector(384),
    )
    # ### end Alembic commands ###
