"""add_file_hash_to_exam_analyses

Revision ID: ebf151330860
Revises: 453fee336f8f
Create Date: 2026-08-13 21:35:01.352109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebf151330860'
down_revision: Union[str, Sequence[str], None] = '453fee336f8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_analyses', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_exam_analyses_file_hash'), 'exam_analyses', ['file_hash'], unique=False)
    op.drop_constraint(op.f('ck_learner_course_profiles_learner_course_profile_versi_1e67'), 'learner_course_profiles', type_='check')
    op.create_check_constraint(op.f('ck_learner_course_profiles_learner_course_profile_version_positive'), 'learner_course_profiles', 'profile_version >= 1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_learner_course_profiles_learner_course_profile_version_positive'), 'learner_course_profiles', type_='check')
    op.create_check_constraint(op.f('ck_learner_course_profiles_learner_course_profile_versi_1e67'), 'learner_course_profiles', 'profile_version >= 1')
    op.drop_index(op.f('ix_exam_analyses_file_hash'), table_name='exam_analyses')
    op.drop_column('exam_analyses', 'file_hash')
    # ### end Alembic commands ###
