"""add_exam_analyses_table

Revision ID: f029c894a90b
Revises: e9b1c3d6f842
Create Date: 2026-08-04 22:21:57.300244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f029c894a90b'
down_revision: Union[str, Sequence[str], None] = 'e9b1c3d6f842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_analyses',
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('ocr_engine', sa.String(length=50), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('formula_count', sa.Integer(), nullable=False),
    sa.Column('questions_json', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_markdown', sa.Text(), nullable=True),
    sa.Column('ai_recommendation_json', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('resources_json', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('mastery_updates_json', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learner_profiles.id'], name=op.f('fk_exam_analyses_learner_id_learner_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_analyses'))
    )
    op.create_index(op.f('ix_exam_analyses_learner_id'), 'exam_analyses', ['learner_id'], unique=False)
    op.drop_index(op.f('ix_content_chunks_embedding_hnsw'), table_name='content_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_constraint(op.f('ck_learner_course_profiles_learner_course_profile_versi_1e67'), 'learner_course_profiles', type_='check')
    op.create_check_constraint(op.f('ck_learner_course_profiles_learner_course_profile_version_positive'), 'learner_course_profiles', 'profile_version >= 1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_learner_course_profiles_learner_course_profile_version_positive'), 'learner_course_profiles', type_='check')
    op.create_check_constraint(op.f('ck_learner_course_profiles_learner_course_profile_versi_1e67'), 'learner_course_profiles', 'profile_version >= 1')
    op.create_index(op.f('ix_content_chunks_embedding_hnsw'), 'content_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_exam_analyses_learner_id'), table_name='exam_analyses')
    op.drop_table('exam_analyses')
    # ### end Alembic commands ###
