"""unify database: drop unused course catalog and adaptive roadmap tables

Revision ID: f475c2e275d3
Revises: d1f56f7e8d01
Create Date: 2026-08-20 21:17:48.101952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy.vector

# revision identifiers, used by Alembic.
revision: str = 'f475c2e275d3'
down_revision: Union[str, Sequence[str], None] = 'd1f56f7e8d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Autogenerate's default drop order isn't FK-safe here: `courses` <-> `course_versions` <->
    # `course_publications` form a genuine reference cycle (courses.active_publication_id ->
    # course_publications, courses.published_version_id -> course_versions, both of which point
    # back to courses). CASCADE sidesteps having to hand-resolve that cycle; the tables being
    # dropped are all being removed together in this migration, so cascading within that set is
    # safe.
    for table_name in (
        "concept_prerequisites",
        "diagnostic_attempts",
        "diagnostic_assessments",
        "content_chunks",
        "course_concepts",
        "course_lessons",
        "course_chapters",
        "document_analyses",
        "document_jobs",
        "documents",
        "course_learning_paths",
        "learner_course_profiles",
        "course_versions",
        "course_publications",
        "courses",
        "roadmap_items",
        "roadmaps",
    ):
        op.execute(f"DROP TABLE IF EXISTS {table_name} CASCADE")

    op.drop_column("exam_analyses", "course_id")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_analyses', sa.Column('course_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_exam_analyses_course_id_courses'), 'exam_analyses', 'courses', ['course_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_exam_analyses_course_id'), 'exam_analyses', ['course_id'], unique=False)
    op.create_table('course_chapters',
    sa.Column('course_version_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source_label', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_version_id'], ['course_versions.id'], name=op.f('fk_course_chapters_course_version_id_course_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_chapters')),
    sa.UniqueConstraint('course_version_id', 'order_index', name=op.f('uq_course_chapters_version_order'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_course_chapters_course_version_id'), 'course_chapters', ['course_version_id'], unique=False)
    op.create_table('course_lessons',
    sa.Column('course_version_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chapter_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source_label', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['course_chapters.id'], name=op.f('fk_course_lessons_chapter_id_course_chapters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_version_id'], ['course_versions.id'], name=op.f('fk_course_lessons_course_version_id_course_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_lessons')),
    sa.UniqueConstraint('chapter_id', 'order_index', name=op.f('uq_course_lessons_chapter_order'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_course_lessons_course_version_id'), 'course_lessons', ['course_version_id'], unique=False)
    op.create_table('roadmap_items',
    sa.Column('roadmap_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('concept_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('sequence', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('session_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('planned_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('estimated_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('activity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], name=op.f('fk_roadmap_items_roadmap_id_roadmaps'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roadmap_items')),
    sa.UniqueConstraint('roadmap_id', 'sequence', name=op.f('uq_roadmap_items_sequence'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_roadmap_items_roadmap_id'), 'roadmap_items', ['roadmap_id'], unique=False)
    op.create_index(op.f('ix_roadmap_items_concept_id'), 'roadmap_items', ['concept_id'], unique=False)
    op.create_table('course_concepts',
    sa.Column('course_version_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('lesson_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('stable_key', sa.VARCHAR(length=180), autoincrement=False, nullable=False),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('estimated_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_version_id'], ['course_versions.id'], name=op.f('fk_course_concepts_course_version_id_course_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['course_lessons.id'], name=op.f('fk_course_concepts_lesson_id_course_lessons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_concepts')),
    sa.UniqueConstraint('course_version_id', 'stable_key', name=op.f('uq_course_concepts_version_stable_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('lesson_id', 'order_index', name=op.f('uq_course_concepts_lesson_order'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_course_concepts_course_version_id'), 'course_concepts', ['course_version_id'], unique=False)
    op.create_table('document_jobs',
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('progress', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_step', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('error_code', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('error_detail', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('progress >= 0 AND progress <= 100', name=op.f('ck_document_jobs_document_job_progress_range')),
    sa.CheckConstraint('retry_count >= 0', name=op.f('ck_document_jobs_document_job_retry_non_negative')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_jobs_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_jobs'))
    )
    op.create_index(op.f('ix_document_jobs_document_id'), 'document_jobs', ['document_id'], unique=False)
    op.create_table('documents',
    sa.Column('course_version_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('storage_key', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('original_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('size_bytes', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('checksum_sha256', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('size_bytes > 0', name=op.f('ck_documents_document_size_positive')),
    sa.ForeignKeyConstraint(['course_version_id'], ['course_versions.id'], name=op.f('fk_documents_course_version_id_course_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_documents_storage_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_documents_course_version_id'), 'documents', ['course_version_id'], unique=False)
    op.create_table('course_publications',
    sa.Column('course_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('revision', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('version_ids_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('quality_snapshot_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('published_by_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('unpublished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_publications_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['published_by_id'], ['users.id'], name=op.f('fk_course_publications_published_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_publications')),
    sa.UniqueConstraint('course_id', 'revision', name=op.f('uq_course_publications_course_revision'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_course_publications_course_id'), 'course_publications', ['course_id'], unique=False)
    op.create_table('diagnostic_attempts',
    sa.Column('assessment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('answers_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('result_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('idempotency_key', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['diagnostic_assessments.id'], name=op.f('fk_diagnostic_attempts_assessment_id_diagnostic_assessments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_diagnostic_attempts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diagnostic_attempts')),
    sa.UniqueConstraint('user_id', 'idempotency_key', name=op.f('uq_diagnostic_attempts_user_idempotency'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_diagnostic_attempts_user_id'), 'diagnostic_attempts', ['user_id'], unique=False)
    op.create_index(op.f('ix_diagnostic_attempts_assessment_id'), 'diagnostic_attempts', ['assessment_id'], unique=False)
    op.create_table('content_chunks',
    sa.Column('course_version_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('character_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('page_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source_label', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding_model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('lesson_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_version_id'], ['course_versions.id'], name=op.f('fk_content_chunks_course_version_id_course_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_content_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['course_lessons.id'], name=op.f('fk_content_chunks_lesson_id_course_lessons'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_chunks')),
    sa.UniqueConstraint('course_version_id', 'chunk_index', name=op.f('uq_content_chunks_version_chunk_index'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_content_chunks_lesson_id'), 'content_chunks', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_content_chunks_course_version'), 'content_chunks', ['course_version_id'], unique=False)
    op.create_table('course_learning_paths',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('publication_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('learner_course_profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('profile_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagnostic_attempt_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('path_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('required_mastery', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total_estimated_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mastery_snapshot_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('gaps_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('skipped_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('items_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('generator', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_learning_paths_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['diagnostic_attempt_id'], ['diagnostic_attempts.id'], name=op.f('fk_course_learning_paths_diagnostic_attempt_id_diagnost_5bd3'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['learner_course_profile_id'], ['learner_course_profiles.id'], name=op.f('fk_course_learning_paths_learner_course_profile_id_lear_f1fd'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['publication_id'], ['course_publications.id'], name=op.f('fk_course_learning_paths_publication_id_course_publications'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_course_learning_paths_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_learning_paths')),
    sa.UniqueConstraint('user_id', 'course_id', 'path_version', name=op.f('uq_course_learning_paths_user_course_version'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_course_learning_paths_user_id'), 'course_learning_paths', ['user_id'], unique=False)
    op.create_index(op.f('ix_course_learning_paths_course_id'), 'course_learning_paths', ['course_id'], unique=False)
    op.create_table('courses',
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('grade_level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('published_version_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('active_publication_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.CheckConstraint('grade_level >= 1 AND grade_level <= 12', name=op.f('ck_courses_course_grade_level_range')),
    sa.ForeignKeyConstraint(['active_publication_id'], ['course_publications.id'], name=op.f('fk_courses_active_publication_id_course_publications'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_courses_owner_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['published_version_id'], ['course_versions.id'], name=op.f('fk_courses_published_version_id_course_versions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses'))
    )
    op.create_index(op.f('ix_courses_subject'), 'courses', ['subject'], unique=False)
    op.create_index(op.f('ix_courses_owner_id'), 'courses', ['owner_id'], unique=False)
    op.create_table('roadmaps',
    sa.Column('learner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('deadline', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('total_estimated_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('profile_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('context_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learner_profiles.id'], name=op.f('fk_roadmaps_learner_id_learner_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roadmaps'))
    )
    op.create_index(op.f('ix_roadmaps_learner_id'), 'roadmaps', ['learner_id'], unique=False)
    op.create_table('learner_course_profiles',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('publication_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('version_ids_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('learning_goal', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('deadline', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('minutes_per_day', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('days_per_week', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('available_periods', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('content_formats', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('profile_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('days_per_week >= 1 AND days_per_week <= 7', name=op.f('ck_learner_course_profiles_learner_course_profile_days_range')),
    sa.CheckConstraint('deadline >= start_date', name=op.f('ck_learner_course_profiles_learner_course_profile_date_order')),
    sa.CheckConstraint('minutes_per_day >= 10 AND minutes_per_day <= 600', name=op.f('ck_learner_course_profiles_learner_course_profile_minutes_range')),
    sa.CheckConstraint('profile_version >= 1', name=op.f('ck_learner_course_profiles_learner_course_profile_versi_1e67')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_learner_course_profiles_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publication_id'], ['course_publications.id'], name=op.f('fk_learner_course_profiles_publication_id_course_publications'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_learner_course_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learner_course_profiles')),
    sa.UniqueConstraint('user_id', 'course_id', name=op.f('uq_learner_course_profiles_user_course'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_learner_course_profiles_user_id'), 'learner_course_profiles', ['user_id'], unique=False)
    op.create_index(op.f('ix_learner_course_profiles_course_id'), 'learner_course_profiles', ['course_id'], unique=False)
    op.create_table('document_analyses',
    sa.Column('course_version_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('source_characters', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('extracted_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('structure_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('error_code', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('error_detail', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('llm_input_text', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('edited_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('edited_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('edited_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('edited_structure_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('structure_edited_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('structure_edited_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_version_id'], ['course_versions.id'], name=op.f('fk_document_analyses_course_version_id_course_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_analyses_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['edited_by_id'], ['users.id'], name=op.f('fk_document_analyses_edited_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['structure_edited_by_id'], ['users.id'], name=op.f('fk_document_analyses_structure_edited_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_analyses')),
    sa.UniqueConstraint('course_version_id', name=op.f('uq_document_analysis_course_version'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_document_analyses_course_version_id'), 'document_analyses', ['course_version_id'], unique=False)
    op.create_table('course_versions',
    sa.Column('course_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('version_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('failure_code', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('failure_detail', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_versions_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_course_versions_created_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_versions')),
    sa.UniqueConstraint('course_id', 'version_number', name=op.f('uq_course_versions_course_version_number'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_course_versions_course_id'), 'course_versions', ['course_id'], unique=False)
    op.create_table('diagnostic_assessments',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('publication_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('learner_course_profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('profile_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assessment_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('questions_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_diagnostic_assessments_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['learner_course_profile_id'], ['learner_course_profiles.id'], name=op.f('fk_diagnostic_assessments_learner_course_profile_id_lea_846c'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['publication_id'], ['course_publications.id'], name=op.f('fk_diagnostic_assessments_publication_id_course_publications'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_diagnostic_assessments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diagnostic_assessments'))
    )
    op.create_index(op.f('ix_diagnostic_assessments_user_id'), 'diagnostic_assessments', ['user_id'], unique=False)
    op.create_index(op.f('ix_diagnostic_assessments_course_id'), 'diagnostic_assessments', ['course_id'], unique=False)
    op.create_table('concept_prerequisites',
    sa.Column('concept_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('prerequisite_concept_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['course_concepts.id'], name=op.f('fk_concept_prerequisites_concept_id_course_concepts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prerequisite_concept_id'], ['course_concepts.id'], name=op.f('fk_concept_prerequisites_prerequisite_concept_id_course_0f21'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_concept_prerequisites')),
    sa.UniqueConstraint('concept_id', 'prerequisite_concept_id', name=op.f('uq_concept_prerequisites_pair'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
